/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackEarth: typeof import('./src/components/background/BackEarth.vue')['default']
    CheckInputProps: typeof import('./src/components/form/CheckInputProps.vue')['default']
    ColorInputProps: typeof import('./src/components/form/ColorInputProps.vue')['default']
    EchartsErrorNoData: typeof import('./src/components/echarts/EchartsErrorNoData.vue')['default']
    EchartsOptionBase: typeof import('./src/components/echarts/EchartsOptionBase.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    EllipsisTextScroll: typeof import('./src/components/common/EllipsisTextScroll.vue')['default']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LatitudeBaseInput: typeof import('./src/components/lnglat/LatitudeBaseInput.vue')['default']
    LongitudeBaseInput: typeof import('./src/components/lnglat/LongitudeBaseInput.vue')['default']
    LongitudeInput: typeof import('./src/components/lnglat/LongitudeInput.vue')['default']
    NumberInputSliderProps: typeof import('./src/components/form/NumberInputSliderProps.vue')['default']
    OffLineTip: typeof import('./src/components/common/OffLineTip.vue')['default']
    OptionsInputProps: typeof import('./src/components/form/OptionsInputProps.vue')['default']
    RjBooleanSwitchInput: typeof import('./src/components/form/RjBooleanSwitchInput.vue')['default']
    RjRadioInput: typeof import('./src/components/form/RjRadioInput.vue')['default']
    RjRadioTabInput: typeof import('./src/components/form/RjRadioTabInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VantaBackEffect: typeof import('./src/components/background/VantaBackEffect.vue')['default']
  }
}
