/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackEarth: typeof import('./src/components/background/BackEarth.vue')['default']
    CheckInputProps: typeof import('./src/components/form/CheckInputProps.vue')['default']
    ColorInputProps: typeof import('./src/components/form/ColorInputProps.vue')['default']
    CommonWraper: typeof import('./src/components/wrapper/CommonWraper.vue')['default']
    EchartsErrorNoData: typeof import('./src/components/echarts/EchartsErrorNoData.vue')['default']
    EchartsOptionBase: typeof import('./src/components/echarts/EchartsOptionBase.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    EllipsisTextScroll: typeof import('./src/components/common/EllipsisTextScroll.vue')['default']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LatitudeBaseInput: typeof import('./src/components/lnglat/LatitudeBaseInput.vue')['default']
    LeftParamsWraper: typeof import('./src/components/wrapper/LeftParamsWraper.vue')['default']
    LongitudeBaseInput: typeof import('./src/components/lnglat/LongitudeBaseInput.vue')['default']
    LongitudeInput: typeof import('./src/components/lnglat/LongitudeInput.vue')['default']
    NumberInputSliderProps: typeof import('./src/components/form/NumberInputSliderProps.vue')['default']
    OffLineTip: typeof import('./src/components/common/OffLineTip.vue')['default']
    OptionsInputProps: typeof import('./src/components/form/OptionsInputProps.vue')['default']
    PureOptionsInput: typeof import('./src/components/form/PureOptionsInput.vue')['default']
    RightParamsWraper: typeof import('./src/components/wrapper/RightParamsWraper.vue')['default']
    RjBooleanSwitchInput: typeof import('./src/components/form/RjBooleanSwitchInput.vue')['default']
    RjRadioInput: typeof import('./src/components/form/RjRadioInput.vue')['default']
    RjRadioTabInput: typeof import('./src/components/form/RjRadioTabInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnitsOptionsInput: typeof import('./src/components/form/UnitsOptionsInput.vue')['default']
    VantaBackEffect: typeof import('./src/components/background/VantaBackEffect.vue')['default']
  }
}
